const fontCheck = new Set(
  [
    "American Typewriter",
    "Andale Mono",
    "Arial Black",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "Arial",
    "Avenir Next Condensed",
    "Avenir Next",
    "Avenir",
    "Bahnschrift",
    "Baskerville",
    "Big Caslon",
    "Bodoni 72 Oldstyle",
    "Bodoni 72 Smallcaps",
    "Bodoni 72",
    "Bradley Hand",
    "Calibri",
    "Cambria",
    "Candara",
    "Chalkboard SE",
    "Chalkboard",
    "Charter",
    "Cochin",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Copperplate",
    "Corbel",
    "Courier New",
    "Courier",
    "Didot",
    "DIN Alternate",
    "DIN Condensed",
    "Ebrima",
    "Franklin Gothic Medium",
    "Futura",
    "Gabriola",
    "Gadugi",
    "Geneva",
    "Georgia",
    "Gill Sans",
    "Helvetica Neue",
    "Helvetica",
    "Herculanum",
    "Hoefler Text",
    "HoloLens MDL2 Assets",
    "Impact",
    "Javanese Text",
    "Leelawadee UI",
    "Lucida Console",
    "Lucida Grande",
    "Lucida Sans Unicode",
    "Luminari",
    "Malgun Gothic",
    "Marker Felt",
    "Menlo",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft Yi Baiti",
    "MingLiU-ExtB",
    "Monaco",
    "Mongolian Baiti",
    "MS Gothic",
    "MV Boli",
    "Myanmar Text",
    "Nirmala UI",
    "Noteworthy",
    "Optima",
    "Palatino Linotype",
    "Palatino",
    "Phosphate",
    "Rockwell",
    "Savoye LET",
    "Segoe MDL2 Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Symbol",
    "Segoe UI",
    "SignPainter",
    "SimSun",
    "Sitka",
    "Skia",
    "Snell Roundhand",
    "Sylfaen",
    "Tahoma",
    "Times New Roman",
    "Times",
    "Trattatello",
    "Trebuchet MS",
    "Verdana",
    "Yu Gothic",
    "Zapfino",
    
  ].sort()
);

export const getAvailableFonts = () => {
  const fontAvailable = new Set();
  fontCheck.forEach(font => {
    if (document.fonts.check(`12px "${font}"`)) {
      fontAvailable.add(font);
    }
  });
  return fontAvailable;
};
